name: 'Auto Approve'
description: 'Automatically approve pull requests'
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
  github-token:
    description: 'The GITHUB_TOKEN secret'
    default: ${{ github.token }}
    required: false
  pull-request-number:
    description: '(optional) The ID of a pull request to auto-approve. By default, this action tries to use the pull_request event payload.'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
